# Generated by Django 4.2.3 on 2023-07-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=20, verbose_name='이름')),
                ('user_number', models.CharField(max_length=5, unique=True, verbose_name='학번')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
            ],
            options={
                'verbose_name': '계정',
                'verbose_name_plural': '계정',
                'db_table': 'Account',
            },
        ),
    ]
